[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[theme]
primaryColor = "#2e7d32"         # 緑っぽい
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F8F4"
textColor = "#000000"
font = "sans serif"

[server]
headless = true
enableXsrfProtection = false
enableCORS = false
address = "0.0.0.0"
port = 10000
